### ISSUE TITLE
Minor CSS Display Fixes

### ISSUE THREAD

**Issue by SamuelJBeer** [overskul/better-ui#6]
I've put together a handful of CSS snippets, with each accompanied by a brief explanation of their roles in correcting some minor display issues  I was experiencing.

```css
/*
 * Ensures the settings > plugin list is
 * rendered uniformly for all tabs.
 */
#plugins.list .list-item,
#plugins .list .list-item {
  min-height: fit-content !important;
}

/*
 * Removed the horizontal padding between the
 * plugin authors name, licence and download
 * count as it's essentially made unnecessary
 * by the middots being present
*/
#plugins .list-item .plugin-meta .plugin-stats {
  margin-right: 0;
}

/* 
 *  For the sake of simplicity, I've elected to
 *  hide the price field altogether.
 */
#plugins .list-item .plugin-header .plugin-info .plugin-price {
  display: none;
  visibility: hidden;
}
```

**Command Palette Fixes:**

```css
/* 
 * Ensures commands palette entries are rendered
 * appropriately regardless of their verbosity
 * and prevents any nested scroller bs occurring.
 */
#hints [data-action='hint'],
#hints [action='hint'] {
  height: auto !important;
  overflow-y: hidden !important;
}

/*
 * Forcibly renders 'Recently used' on a separate line
 * of its own, rather than appending it to the command
 * description and subsequently wrapping where ever
 * it pleases.
 */
#hints [data-action='hint'] [data-str]::after,
#hints [action='hint'] [data-str]::after {
  content: "\A" attr(data-str);
  white-space: pre;
}
```
